SELECT * FROM EDSR.HPRANGOPRECIO WHERE AKU = '126919'
SELECT * FROM EDSR.DCP_PRODUCTO
SELECT * FROM EDSR.CSTMSTEE

SELECT * FROM EDSR.GRE_MODELO_WMS;
SELECT * FROM EDSR.GRE_MODELO_DAD;

SELECT * FROM EDSR.GRE_PAQUETE_ORIGEN;
SELECT * FROM EDSR.GRE_PAQUETE_TIPO;
SELECT * FROM EDSR.GRE_PAQUETE_EST;
SELECT * FROM EDSR.GRE_PAQUETE;
SELECT * FROM EDSR.GRE_PAQUETE_GUIA WHERE NU_ID_PAQUETE = 155769;
SELECT * FROM EDSR.GRE_PAQUETE_GUIA_DET;
SELECT * FROM EDSR.GRE_PAQUETE_GUIA_ERROR;

SELECT * FROM EDSR.GRE_NRO_DOC_IDENTIDAD_INVALIDO;

SELECT * FROM EDSR.GRE_GUIA_EST;
SELECT * FROM EDSR.GRE_GUIA;
SELECT * FROM EDSR.GRE_GUIA_DET;
SELECT * FROM EDSR.GRE_GUIA_CONSULTA_SOVOS;
