select 
Prod.ITEM_NUMBER IdPim,
P.DESCRIPTION NombreProducto,
'TIPO_DE_NEGOCIACION' TipoNegociacion,
AtComercial.ATTRIBUTE_CHAR10 AtCom10,
'TIPO_DE_MARCA' TipoMarca,
AtComercial.ATTRIBUTE_CHAR16,
'CLUSTER_DE_SURTIDO' ClusterSurtido,
AtSurt.ATTRIBUTE_CHAR1,
'LONGTAIL' LONGTAIL,
AtSurt.ATTRIBUTE_CHAR3 AtrSurt3,
'TIPO_DE_SURTIDO' TipoSurtido,
AtComercial2.ATTRIBUTE_CHAR7,
'PUNTO_DE_PRECIO' PtoPrecio,
AtComercial2.ATTRIBUTE_CHAR11,
'AFECTO_DETRACCION' AfectoDetr,
AtContab.ATTRIBUTE_CHAR2,
'AFECTO_IGV' AfectoIGV,
AtContab.ATTRIBUTE_CHAR3 AtrContab3,
'MARCA' MARCA,
AtAprob.ATTRIBUTE_CHAR8 AtAprob8,
'DESPACHO_CD' DespachoCD,
AtLogist.ATTRIBUTE_CHAR3,
'PERECIBLE' Perecible,
AtLogist.ATTRIBUTE_CHAR4,
'BIG_TICKET' BigTicket,
AtLogist.ATTRIBUTE_CHAR8 AtLog8,
'PRODUCTOS_SENSIBLES' ProdSensibl,
AtLogist.ATTRIBUTE_CHAR10 AtLog10,
'EMPIOCHADO' Empiochado,
AtLogist.ATTRIBUTE_CHAR15
from EGP_SYSTEM_ITEMS_B Prod
left join EGP_SYSTEM_ITEMS_TL P on Prod.INVENTORY_ITEM_ID = P.INVENTORY_ITEM_ID 
left join EGO_ITEM_EFF_B AtComercial on Prod.INVENTORY_ITEM_ID = AtComercial.INVENTORY_ITEM_ID and AtComercial.CONTEXT_CODE = 'HPSA_ATRIBUTOS_COMERCIALES'
left join EGO_ITEM_EFF_B AtSurt on Prod.INVENTORY_ITEM_ID = AtSurt.INVENTORY_ITEM_ID and AtSurt.CONTEXT_CODE = 'HPSA_ATRIBUTOS_DE_SURTIDO'
left join EGO_ITEM_EFF_B AtComercial2 on Prod.INVENTORY_ITEM_ID = AtComercial2.INVENTORY_ITEM_ID and AtComercial2.CONTEXT_CODE = 'HPSA_ATRIBUTOS_COMERCIALES_2'
left join EGO_ITEM_EFF_B AtContab on Prod.INVENTORY_ITEM_ID = AtContab.INVENTORY_ITEM_ID and AtContab.CONTEXT_CODE = 'HPSA_ATRIBUTOS_CONTABLES'
left join EGO_ITEM_EFF_B AtAprob on Prod.INVENTORY_ITEM_ID = AtAprob.INVENTORY_ITEM_ID and AtAprob.CONTEXT_CODE = 'HPSA_APROBACION_FINAL'
left join EGO_ITEM_EFF_B AtLogist on Prod.INVENTORY_ITEM_ID = AtLogist.INVENTORY_ITEM_ID and AtLogist.CONTEXT_CODE = 'HPSA_ATRIBUTOS_LOGISTICOS'
where Prod.ITEM_NUMBER like 'PROMART%'
and Prod.ACD_TYPE= 'PROD'
and P.LANGUAGE = 'E'
and rownum < 4


