SELECT * FROM EDSR.PIM_MODELO
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = 0, FLG_ERROR = 0 , MENSAJE = ''
--WHERE ID_MODELO = 502
ORDER BY 4 DESC


SELECT * FROM EDSR.PIM_PRODUCTO ORDER BY 5 DESC
 
SELECT * FROM EDSR.PIM_PRODUCTO_ATRIB

SELECT upc_type FROM EDSR.SDIPRDUPI
